#!/usr/bin/env npx tsx
/**
 * bundle-manifests.ts — Generates a TypeScript module with base64-encoded encrypted manifests.
 *
 * This bundle is imported by the Vercel scoring API. The encrypted data is useless
 * without the passphrase (stored only in Vercel env vars, never in the repo).
 *
 * Usage:
 *   npx tsx _scoring/bundle-manifests.ts
 *   npx tsx _scoring/bundle-manifests.ts --out trashfire.io/api/_manifests.ts
 */

import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join, basename } from "node:path";

const ROOT = join(import.meta.dirname ?? ".", "..");
const MANIFESTS_DIR = join(ROOT, "_manifests");
const DEFAULT_OUT = join(ROOT, "trashfire.io", "api", "_manifests.ts");

function main() {
  const args = process.argv.slice(2);
  const outIndex = args.indexOf("--out");
  const outPath = outIndex !== -1 ? args[outIndex + 1] : DEFAULT_OUT;

  // Read all .enc files
  const encFiles = readdirSync(MANIFESTS_DIR)
    .filter(f => f.endsWith(".enc"))
    .sort();

  if (encFiles.length === 0) {
    console.error("No .enc files found in _manifests/");
    process.exit(1);
  }

  console.log(`Bundling ${encFiles.length} encrypted manifests...`);

  const entries: string[] = [];
  let totalBytes = 0;

  for (const file of encFiles) {
    const project = basename(file, ".enc");
    const data = readFileSync(join(MANIFESTS_DIR, file));
    const b64 = data.toString("base64");
    entries.push(`  "${project}": "${b64}",`);
    totalBytes += data.length;
    console.log(`  ${project}: ${data.length} bytes`);
  }

  const output = `// Auto-generated by _scoring/bundle-manifests.ts
// Contains ${encFiles.length} AES-256-GCM encrypted manifests (base64-encoded).
// These are useless without the passphrase (stored in TRASHFIRE_KEY env var).
// DO NOT commit the passphrase. DO NOT decrypt these client-side.
//
// Regenerate: npx tsx _scoring/bundle-manifests.ts

export const MANIFESTS: Record<string, string> = {
${entries.join("\n")}
};

export const MANIFEST_PROJECTS = Object.keys(MANIFESTS).sort();
`;

  writeFileSync(outPath, output);
  console.log(`\nBundle written to ${outPath}`);
  console.log(`  Projects: ${encFiles.length}`);
  console.log(`  Total encrypted data: ${(totalBytes / 1024).toFixed(0)} KB`);
  console.log(`  Bundle size: ${(output.length / 1024).toFixed(0)} KB`);
}

main();
