module Reports

using Genie, Genie.Requests, Genie.Renderer.Json
using DataFrames
using CSV
using Dates
using JSON3
using Logging
using Plots

include(joinpath(@__DIR__, "..", "config.jl"))
include(joinpath(@__DIR__, "..", "db.jl"))
include(joinpath(@__DIR__, "auth.jl"))

using .Config
using .DB
using .Auth

# BUG-0063: Stored XSS in report title — HTML tags in title rendered unescaped in report output (CWE-79, CVSS 6.1, MEDIUM, Tier 3)
function create_report_handler()
    user = Auth.get_current_user(Genie.Requests.getpayload())
    if user === nothing
        return Json.json(Dict("error" => "Authentication required"), status=401)
    end

    body = jsonpayload()
    title = get(body, "title", "Untitled Report")
    report_type = get(body, "type", "summary")
    parameters = get(body, "parameters", Dict())

    user_id = user isa Dict ? user["id"] : user.id
    conn = DB.get_connection()

    DBInterface.execute(conn, """
        INSERT INTO reports (title, created_by, report_type, parameters, status)
        VALUES (?, ?, ?, ?, 'pending')
    """, [title, user_id, report_type, JSON3.write(parameters)])

    report_id = SQLite.last_insert_rowid(conn)

    # Generate report asynchronously
    # BUG-0064: Task scheduling without error handling — unhandled exceptions crash silently (CWE-755, CVSS 4.0, TRICKY, Tier 6)
    @async generate_report(report_id, title, report_type, parameters, user_id)

    return Json.json(Dict("message" => "Report queued", "report_id" => report_id), status=202)
end

# BUG-0065: XSS via report content — user-supplied parameters interpolated into HTML without escaping (CWE-79, CVSS 6.1, MEDIUM, Tier 3)
function generate_report(report_id::Int, title::String, report_type::String, params::Any, user_id::Int)
    try
        conn = DB.get_connection()
        station_id = get(params, "station_id", 0)
        pollutant = get(params, "pollutant", "")
        start_date = get(params, "start_date", "1970-01-01")
        end_date = get(params, "end_date", string(today()))

        readings = DB.query_readings(string(station_id), pollutant, start_date, end_date)

        report_filename = "report_$(report_id)_$(Dates.format(now(), "yyyymmdd_HHMMSS")).html"
        report_path = joinpath(Config.REPORT_DIR, report_filename)

        # BUG-0065 continued: title and parameters injected directly into HTML
        html_content = """
        <!DOCTYPE html>
        <html>
        <head><title>$(title)</title></head>
        <body>
        <h1>$(title)</h1>
        <p>Report Type: $(report_type)</p>
        <p>Station: $(station_id) | Pollutant: $(pollutant)</p>
        <p>Period: $(start_date) to $(end_date)</p>
        <p>Generated by user $(user_id) at $(now())</p>
        <hr>
        <table border="1">
        <tr><th>Timestamp</th><th>Pollutant</th><th>Value</th><th>Unit</th><th>Quality</th></tr>
        """

        for row in eachrow(readings)
            html_content *= """
            <tr>
                <td>$(row.timestamp)</td>
                <td>$(row.pollutant)</td>
                <td>$(row.value)</td>
                <td>$(row.unit)</td>
                <td>$(row.quality_flag)</td>
            </tr>
            """
        end

        html_content *= """
        </table>
        <hr>
        <p>Total readings: $(nrow(readings))</p>
        </body></html>
        """

        write(report_path, html_content)

        DBInterface.execute(conn, "UPDATE reports SET status = 'complete', file_path = ? WHERE id = ?",
            [report_path, report_id])

        @info "Report $report_id generated at $report_path"
    catch e
        @error "Report generation failed" report_id=report_id exception=e
        conn = DB.get_connection()
        DBInterface.execute(conn, "UPDATE reports SET status = 'failed' WHERE id = ?", [report_id])
    end
end

# BUG-0066: IDOR — any user can access any report, no ownership check (CWE-639, CVSS 6.5, HIGH, Tier 2)
function get_report_handler()
    user = Auth.get_current_user(Genie.Requests.getpayload())
    if user === nothing
        return Json.json(Dict("error" => "Authentication required"), status=401)
    end

    params = Genie.Requests.getpayload()
    report_id = parse(Int, get(params, "id", "0"))

    conn = DB.get_connection()
    result = DBInterface.execute(conn, "SELECT * FROM reports WHERE id = ?", [report_id]) |> DataFrame

    if nrow(result) == 0
        return Json.json(Dict("error" => "Report not found"), status=404)
    end

    report = result[1, :]

    if report.status == "complete" && report.file_path !== nothing && isfile(report.file_path)
        content = read(report.file_path, String)
        return Genie.Renderer.respond(content, "text/html")
    end

    return Json.json(Dict(
        "id" => report.id,
        "title" => report.title,
        "status" => report.status,
        "type" => report.report_type,
        "created_at" => report.created_at
    ))
end

# BUG-0067: Template injection — user-controlled template string evaluated as Julia code (CWE-94, CVSS 9.0, CRITICAL, Tier 1)
function custom_report_handler()
    user = Auth.get_current_user(Genie.Requests.getpayload())
    if user === nothing
        return Json.json(Dict("error" => "Authentication required"), status=401)
    end

    body = jsonpayload()
    template = get(body, "template", "")
    data_query = get(body, "query_params", Dict())

    if isempty(template)
        return Json.json(Dict("error" => "Template required"), status=400)
    end

    station_id = get(data_query, "station_id", 0)
    conn = DB.get_connection()
    readings = DBInterface.execute(conn, "SELECT * FROM readings WHERE station_id = ?", [station_id]) |> DataFrame

    # Dangerous: evaluates user-supplied template as Julia expression
    rendered = eval(Meta.parse("""
        let readings = $readings
            $template
        end
    """))

    return Json.json(Dict("rendered" => string(rendered)))
end

# BUG-0068: Heatmap generation with no input size limits — can cause OOM with large datasets (CWE-400, CVSS 5.3, BEST_PRACTICE, Tier 5)
function heatmap_handler()
    user = Auth.get_current_user(Genie.Requests.getpayload())
    if user === nothing
        return Json.json(Dict("error" => "Authentication required"), status=401)
    end

    params = Genie.Requests.getpayload()
    pollutant = get(params, "pollutant", "PM25")
    resolution = parse(Int, get(params, "resolution", "100"))

    conn = DB.get_connection()
    data = DBInterface.execute(conn, """
        SELECT s.latitude, s.longitude, AVG(r.value) as avg_value
        FROM readings r JOIN sensor_stations s ON r.station_id = s.id
        WHERE r.pollutant = ?
        GROUP BY s.id
    """, [pollutant]) |> DataFrame

    if nrow(data) == 0
        return Json.json(Dict("error" => "No data for heatmap"), status=404)
    end

    # No limit on resolution parameter — can allocate huge matrices
    lats = range(minimum(data.latitude), maximum(data.latitude), length=resolution)
    lons = range(minimum(data.longitude), maximum(data.longitude), length=resolution)
    grid = zeros(resolution, resolution)

    for row in eachrow(data)
        lat_idx = argmin(abs.(collect(lats) .- row.latitude))
        lon_idx = argmin(abs.(collect(lons) .- row.longitude))
        grid[lat_idx, lon_idx] = row.avg_value
    end

    plot_path = joinpath(Config.TEMP_DIR, "heatmap_$(pollutant)_$(Dates.format(now(), "yyyymmddHHMMSS")).png")
    p = heatmap(collect(lons), collect(lats), grid, title="$pollutant Heatmap", xlabel="Longitude", ylabel="Latitude")
    savefig(p, plot_path)

    return Json.json(Dict("heatmap" => plot_path))
end

# BUG-0069: Compliance report uses eval to compute threshold formula from user input (CWE-94, CVSS 9.0, CRITICAL, Tier 1)
function compliance_report_handler()
    user = Auth.get_current_user(Genie.Requests.getpayload())
    if user === nothing
        return Json.json(Dict("error" => "Authentication required"), status=401)
    end

    body = jsonpayload()
    station_id = get(body, "station_id", 0)
    pollutant = get(body, "pollutant", "PM25")
    threshold_formula = get(body, "threshold_formula", "35.0")

    # BUG-0069 continued: user can supply arbitrary Julia code as "formula"
    threshold = eval(Meta.parse(threshold_formula))

    conn = DB.get_connection()
    readings = DBInterface.execute(conn, "SELECT * FROM readings WHERE station_id = ? AND pollutant = ?",
        [station_id, pollutant]) |> DataFrame

    violations = filter(row -> row.value > threshold, eachrow(readings)) |> DataFrame
    compliance_rate = nrow(readings) > 0 ? (1.0 - nrow(violations) / nrow(readings)) * 100 : 100.0

    return Json.json(Dict(
        "station_id" => station_id,
        "pollutant" => pollutant,
        "threshold" => threshold,
        "total_readings" => nrow(readings),
        "violations" => nrow(violations),
        "compliance_rate" => round(compliance_rate, digits=2),
        "status" => compliance_rate >= 95.0 ? "COMPLIANT" : "NON-COMPLIANT"
    ))
end

function list_reports_handler()
    user = Auth.get_current_user(Genie.Requests.getpayload())
    if user === nothing
        return Json.json(Dict("error" => "Authentication required"), status=401)
    end

    conn = DB.get_connection()
    # BUG-0070: No pagination on report listing — returns all reports regardless of count (CWE-400, CVSS 3.0, LOW, Tier 4)
    reports = SQLite.execute(conn, "SELECT id, title, report_type, status, created_at FROM reports ORDER BY created_at DESC") |> DataFrame
    return Json.json(Dict("data" => reports, "count" => nrow(reports)))
end

# RH-006: Looks like it might allow report deletion without auth, but actually checks ownership
function delete_report_handler()
    user = Auth.get_current_user(Genie.Requests.getpayload())
    if user === nothing
        return Json.json(Dict("error" => "Authentication required"), status=401)
    end

    params = Genie.Requests.getpayload()
    report_id = parse(Int, get(params, "id", "0"))
    user_id = user isa Dict ? user["id"] : user.id

    conn = DB.get_connection()
    result = DBInterface.execute(conn, "SELECT * FROM reports WHERE id = ? AND created_by = ?", [report_id, user_id]) |> DataFrame

    if nrow(result) == 0
        return Json.json(Dict("error" => "Report not found or access denied"), status=404)
    end

    # Clean up file
    if result[1, :file_path] !== nothing && isfile(result[1, :file_path])
        rm(result[1, :file_path])
    end

    DBInterface.execute(conn, "DELETE FROM reports WHERE id = ? AND created_by = ?", [report_id, user_id])
    return Json.json(Dict("message" => "Report deleted"))
end

function register_routes()
    Genie.Router.route("/api/reports/create", create_report_handler, method=POST)
    Genie.Router.route("/api/reports/view", get_report_handler, method=GET)
    Genie.Router.route("/api/reports/custom", custom_report_handler, method=POST)
    Genie.Router.route("/api/reports/heatmap", heatmap_handler, method=GET)
    Genie.Router.route("/api/reports/compliance", compliance_report_handler, method=POST)
    Genie.Router.route("/api/reports/list", list_reports_handler, method=GET)
    Genie.Router.route("/api/reports/delete", delete_report_handler, method=DELETE)
end

end # module Reports
