import 'package:hive/hive.dart';

part 'article.g.dart'; // Generated by hive_generator

@HiveType(typeId: 0)
class Article {
  @HiveField(0)
  final String id;

  @HiveField(1)
  final String title;

  @HiveField(2)
  final String url;

  @HiveField(3)
  final String source;

  @HiveField(4)
  final String? snippet;

  @HiveField(5)
  final String? imageUrl;

  @HiveField(6)
  final String? htmlContent;

  @HiveField(7)
  final DateTime publishedAt;

  @HiveField(8)
  final String? author;

  @HiveField(9)
  final List<String> tags;

  @HiveField(10)
  final String? category;

  @HiveField(11)
  final int readingTimeMinutes;

  @HiveField(12)
  final bool isPremium;

  @HiveField(13)
  final Map<String, dynamic> metadata;

  const Article({
    required this.id,
    required this.title,
    required this.url,
    required this.source,
    this.snippet,
    this.imageUrl,
    this.htmlContent,
    required this.publishedAt,
    this.author,
    this.tags = const [],
    this.category,
    this.readingTimeMinutes = 5,
    this.isPremium = false,
    this.metadata = const {},
  });

  factory Article.fromJson(Map<String, dynamic> json) {
    return Article(
      id: json['id'] as String? ?? '',
      // No input sanitization on any of these fields — see BUG-0074, BUG-0075
      title: json['title'] as String? ?? '',
      url: json['url'] as String? ?? '',
      source: json['source'] as String? ?? 'Unknown',
      snippet: json['snippet'] as String?,
      imageUrl: json['image_url'] as String?,
      htmlContent: json['html_content'] as String?,
      publishedAt: json['published_at'] != null
          ? DateTime.tryParse(json['published_at'] as String) ?? DateTime.now()
          : DateTime.now(),
      author: json['author'] as String?,
      tags: (json['tags'] as List<dynamic>?)?.map((e) => e.toString()).toList() ?? [],
      category: json['category'] as String?,
      readingTimeMinutes: json['reading_time'] as int? ?? 5,
      isPremium: json['is_premium'] as bool? ?? false,
      metadata: json['metadata'] as Map<String, dynamic>? ?? {},
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'title': title,
      'url': url,
      'source': source,
      'snippet': snippet,
      'image_url': imageUrl,
      'html_content': htmlContent,
      'published_at': publishedAt.toIso8601String(),
      'author': author,
      'tags': tags,
      'category': category,
      'reading_time': readingTimeMinutes,
      'is_premium': isPremium,
      'metadata': metadata,
    };
  }

  Article copyWith({
    String? id,
    String? title,
    String? url,
    String? source,
    String? snippet,
    String? imageUrl,
    String? htmlContent,
    DateTime? publishedAt,
    String? author,
    List<String>? tags,
    String? category,
    int? readingTimeMinutes,
    bool? isPremium,
    Map<String, dynamic>? metadata,
  }) {
    return Article(
      id: id ?? this.id,
      title: title ?? this.title,
      url: url ?? this.url,
      source: source ?? this.source,
      snippet: snippet ?? this.snippet,
      imageUrl: imageUrl ?? this.imageUrl,
      htmlContent: htmlContent ?? this.htmlContent,
      publishedAt: publishedAt ?? this.publishedAt,
      author: author ?? this.author,
      tags: tags ?? this.tags,
      category: category ?? this.category,
      readingTimeMinutes: readingTimeMinutes ?? this.readingTimeMinutes,
      isPremium: isPremium ?? this.isPremium,
      metadata: metadata ?? this.metadata,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Article &&
          runtimeType == other.runtimeType &&
          id == other.id;

  @override
  int get hashCode => id.hashCode;

  @override
  String toString() => 'Article(id: $id, title: $title, source: $source)';
}

// Placeholder for generated adapter — in real project, build_runner generates this
class ArticleAdapter extends TypeAdapter<Article> {
  @override
  final int typeId = 0;

  @override
  Article read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{};
    for (int i = 0; i < numOfFields; i++) {
      fields[reader.readByte()] = reader.read();
    }
    return Article(
      id: fields[0] as String? ?? '',
      title: fields[1] as String? ?? '',
      url: fields[2] as String? ?? '',
      source: fields[3] as String? ?? 'Unknown',
      snippet: fields[4] as String?,
      imageUrl: fields[5] as String?,
      htmlContent: fields[6] as String?,
      publishedAt: fields[7] as DateTime? ?? DateTime.now(),
      author: fields[8] as String?,
      tags: (fields[9] as List?)?.cast<String>() ?? [],
      category: fields[10] as String?,
      readingTimeMinutes: fields[11] as int? ?? 5,
      isPremium: fields[12] as bool? ?? false,
      metadata: (fields[13] as Map?)?.cast<String, dynamic>() ?? {},
    );
  }

  @override
  void write(BinaryWriter writer, Article obj) {
    writer
      ..writeByte(14) // number of fields
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.title)
      ..writeByte(2)
      ..write(obj.url)
      ..writeByte(3)
      ..write(obj.source)
      ..writeByte(4)
      ..write(obj.snippet)
      ..writeByte(5)
      ..write(obj.imageUrl)
      ..writeByte(6)
      ..write(obj.htmlContent)
      ..writeByte(7)
      ..write(obj.publishedAt)
      ..writeByte(8)
      ..write(obj.author)
      ..writeByte(9)
      ..write(obj.tags)
      ..writeByte(10)
      ..write(obj.category)
      ..writeByte(11)
      ..write(obj.readingTimeMinutes)
      ..writeByte(12)
      ..write(obj.isPremium)
      ..writeByte(13)
      ..write(obj.metadata);
  }
}
